security:
    encoders:
        ApiBundle\Entity\User:
            algorithm: md5
            iterations: 1
            encode_as_base64: false
    firewalls:
        secured_area:
            pattern: ^/
            stateless: true
            anonymous: true
            simple_preauth:
                authenticator: apibundle.security.access_token_authenticator

    providers:
        access_token:
            id: apibundle.security.access_token_user_provider
