services:
    kernel.listener.json_response_listener :
        class:     ApiBundle\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
