services:
    cache:
        class: Doctrine\Common\Cache\ArrayCache
    # Listeners
    kernel.listener.json_response_listener :
        class: ApiBundle\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    kernel.listener.consumer_authentication_listener :
        class: ApiBundle\Listener\ConsumerAuthenticationListener
        arguments: ['@apibundle.service.consumer_service', '@kernel.listener.exception_listener']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.exception_listener:
        class: ApiBundle\Listener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Security
    apibundle.security.access_token_user_provider:
        class: ApiBundle\Security\AccessTokenUserProvider
        arguments: ['@apibundle.service.access_token_service', '@apibundle.service.user_service']

    apibundle.security.access_token_authenticator:
        class:  ApiBundle\Security\AccessTokenAuthenticator
        public: false

    # Services
    apibundle.service.consumer_service:
        class: ApiBundle\Service\ConsumerService

    apibundle.service.access_token_service:
        class: ApiBundle\Service\AccessTokenService
        arguments: ['@doctrine_cache.providers.redis_session']

    apibundle.service.user_service:
        class: ApiBundle\Service\UserService
        arguments: ['@security.encoder_factory', '@doctrine.orm.default_entity_manager', '@apibundle.repository.user_repository']

    # Repositories
    apibundle.repository.user_repository:
        class: ApiBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['@doctrine.orm.default_entity_manager']